"""Change embedding dimension to 384

Revision ID: b79ee6c8ae25
Revises: fd4969cd9550
Create Date: 2026-09-02 14:08:47.885090

"""
from collections.abc import Sequence

import pgvector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b79ee6c8ae25'
down_revision: str | Sequence[str] | None = 'fd4969cd9550'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
